# Generated by Django 3.2.15 on 2023-04-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_alter_partner_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='owner',
        ),
    ]
